<a href="https://colab.research.google.com/github/sm1118sm/Data_Analysis/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
#파일을 불러오되 꽃받침길이, 꽃받침넓이, 꽃잎길이 컬럼만 불러온 후 첫 번째 행부터 10건을 추출하여 출력하세요

import numpy as np
from google.colab import files

uploaded = files.upload()
file_name = list(uploaded.keys())[0]
file1 = np.loadtxt(file_name, delimiter=',', skiprows=1, usecols=[0,1,2], encoding='cp949')
data2 = file1[0:10]
array3 = np.array(data2)
array3

Saving 붓꽃_최종.csv to 붓꽃_최종 (10).csv


array([[4.6, 3.1, 1.5],
       [5. , 3.6, 1.4],
       [5.4, 3.9, 1.7],
       [4.6, 3.4, 1.4],
       [5. , 3.4, 1.5],
       [4.4, 2.9, 1.4],
       [4.9, 3.1, 1.5],
       [5.4, 3.7, 1.5],
       [4.8, 3.4, 1.6],
       [4.8, 3. , 1.4]])

In [23]:
#파일 2개를 불러와서 각각의 변수에 저장 후 하나의 행렬로 만들고 첫 번째 행부터 10건을 출력하세요 총 행수와 컬럼수를 출력하세요.

import numpy as np
from google.colab import files

uploaded = files.upload()
uploaded2 = files.upload()
file_name = list(uploaded.keys())[0]
file_name2 = list(uploaded2.keys())[0]
file1 = np.loadtxt(file_name, delimiter=',', skiprows=1, encoding='cp949')
file2 = np.loadtxt(file_name2, delimiter=',', skiprows=1, encoding='cp949')
data2 = file1[:]
data3 = file2[:]
array3 = np.array(data2)
array4 = np.array(data3)
array5 = np.hstack([array3, array4])
print(array5[0:10])
print()
print(array5.shape)

Saving 붓꽃_꽃잎정보.csv to 붓꽃_꽃잎정보 (10).csv


Saving 붓꽃_꽃받침정보.csv to 붓꽃_꽃받침정보 (10).csv
[[1.5 0.2 4.6 3.1]
 [1.4 0.2 5.  3.6]
 [1.7 0.4 5.4 3.9]
 [1.4 0.3 4.6 3.4]
 [1.5 0.2 5.  3.4]
 [1.4 0.2 4.4 2.9]
 [1.5 0.1 4.9 3.1]
 [1.5 0.2 5.4 3.7]
 [1.6 0.2 4.8 3.4]
 [1.4 0.1 4.8 3. ]]

(147, 4)
